# Numpy 

## What is a NumPy ?

NumPy is a module for Python. The name is an acronym for "Numeric Python" or "Numerical Python". It is an extension module for Python, mostly written in C. This makes sure that the precompiled mathematical and numerical functions and functionalities of Numpy guarantee great execution speed.

Furthermore, NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays. The implementation is even aiming at huge matrices and arrays, better know under the heading of "big data". Besides that the module supplies a large library of high-level mathematical functions to operate on these matrices and arrays.

SciPy (Scientific Python) is often mentioned in the same breath with NumPy. SciPy needs Numpy, as it is based on the data structures of Numpy and furthermore its basic creation and manipulation functions. It extends the capabilities of NumPy with further useful functions for minimization, regression, Fourier-transformation and many other

![](https://cdn-s-www.estrepublicain.fr/images/C3A82509-DF28-49D8-9CC6-81DB1E24FECB/NW_raw/le-programme-de-la-soiree-organisee-samedi-par-out-of-cinema-a-mulhouse-est-aussi-vague-que-les-lignes-de-code-de-l-affiche-du-film-qui-l-a-inspiree-matrix-photo-dr-1532350200.jpg)


## Enter the matrix
**What's a matrix?**  
A matrix is simply an array with one or more dimensions, containing a number of values.  
A matrix (n × m) is a table of numbers with n rows and m columns: 

\begin{bmatrix}
1&2&7\\
7&1&-5\\
\end{bmatrix}

**`n` and `m` are the dimensions of the matrix**  
A matrix is symbolised by a letter in bold type, e.g. A.   
Note `Aij` is the element at the intersection of row i and column j (the row is always named first).

In this case, the matrix has a dimension of 2 lines on 3 columns.  
Shape of `A` is (2,3)

*If m = 1, the matrix is called a vector (more precisely a column vector) :*  

\begin{bmatrix} 
1\\
7\\
9\\
5\\
\end{bmatrix}



By convention, we will use uppercase letters for matrices and lowercase letters for vectors, but this is not mandatory. **x** = [...]

*If `n = m` the matrix is called **square matrix**:* 

This example show a matrix with (4x4)  :
\begin{bmatrix}
1&2&7&9\\
7&1&-5&3\\
6&4&1&0\\
8&3&2&9\\
\end{bmatrix}


Some particular square matrices :

**Unit Matrix :**
\begin{bmatrix}
1&0&0&0\\
0&1&0&0\\
0&0&1&0\\
0&0&0&1\\
\end{bmatrix}

**Diagonal matrix :**  
\begin{bmatrix}a_{11}&0&0\\0&a_{22}&0\\0&0&a_{33}\end{bmatrix}

**Lower triangular matrix :**
\begin{bmatrix}a_{11}&0&0\\a_{21}&a_{22}&0\\a_{31}&a_{32}&a_{33}\end{bmatrix}

**Upper triangular matrix :** 
\begin{bmatrix}a_{11}&a_{12}&a_{13}\\0&a_{22}&a_{23}\\0&0&a_{33}\end{bmatrix}

Square matrices are often used to represent simple linear transformations, such as shearing or rotation. For example, if {\displaystyle R}R is a square matrix representing a rotation (rotation matrix) and v is a column vector describing the position of a point in space, the product Rv yields another column vector describing the position of that point after that rotation.

## Matrix operations

### Addition and subtraction
Subtraction and addition operations are really very simple on matrices.   
The addition and subtraction of matrices is done from element to element.   
**The matrices must have the same dimensions :**

![calc matrix](https://www.unilim.fr/pages_perso/jean.debord/math/matrices/addsub.gif)

### Multiplication 

With this tool, you can multiply two matrices in line to obtain their product matrix. Dies A and B can even be of dimensions 4, 5 or more. To be able to make the product of two matrices A and B, the number of columns of matrix A must be equal to the number of rows of matrix B. Thus, the dimensions of matrices A and B must be (n,m) and (m,p) respectively. The product matrix AB will then have dimension (n,p) (see product examples below on this page).


![multi](mult1.png)

For this reason, the number of columns in array A should correspond to the number of rows in array B. In this case, array A has a dimension of (2.3) and array B has a dimension of (3.2). Result of C  :
\begin{bmatrix}22&28\\49&64\end{bmatrix}

Here is another example with two arrays of the same dimension!  
![](assets/mult.png)

## Now let's get down to business.

First, import Numpy !

In [1]:
import numpy as np

### Creating arrays
Let's create an array numpy with two rows and three columns.

In [2]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

The dimensions of the array can be displayed using the shape property

In [3]:
A.shape

(2, 3)

### np.zeros

The zeros function creates an array containing any number of zeros:

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

It's just as easy to create a 2D array (ie. a matrix) by providing a tuple with the desired number of rows and columns. For example, here's a 2x3 matrix:

In [5]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### np.ones

We can do the same thing with an array filled with 1

In [6]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.arange

We can also create an array with a range. 

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Like the range() function in python, we can also indicate the start point, the end point and the step.  
``np.arange(start, end, step)``

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### Some vocabulary
* In NumPy, each dimension is called an axis.
* The number of axes is called the rank.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the shape of the array.
    * For example, the above matrix's shape is (3, 4).
    * The rank is equal to the shape's length.
* The size of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

### np.linspace

Create an array of 5 numbers, linearly spaced between 0 and 1

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### np.eye

Returns the identity matrix of size 3. An identity matrix return a 2-D array with ones on the diagonal and zeros elsewhere.

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
a.shape

(3, 4)

In [13]:
a.ndim # equal of len(a)

2

In [14]:
a.size

12

### np.concatenate

Concetrate or join arrays


In [15]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])



array([1, 2, 3, 3, 2, 1])

If the arrays are multidimensional, you can use either vstack  (vertical) or  hstack  (horizontal).


In [16]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

### N-dimensional arrays

You can also create an N-dimensional array of arbitrary rank. For example, here's a 3D array (rank=3), with shape (2,3,4):

In [17]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Array type
NumPy arrays have the type ndarrays:

In [18]:
type(np.zeros((2,3,4)))

numpy.ndarray

### np.full
Creates an array of the given shape initialized with the given value. Here's a 3x4 matrix full of π.

In [19]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

### np.empty
An uninitialized 2x3 array (its content is not predictable, as it is whatever is in memory at that point):

In [20]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.random
A number of functions are available in NumPy's random module to create ndarrays initialized with random values. For example, here is a 3x4 matrix initialized with random floats between 0 and 1 (uniform distribution):

In [21]:
np.random.random((3,4))

array([[0.21064871, 0.51084367, 0.04462232, 0.15474993],
       [0.48943545, 0.17311007, 0.6829123 , 0.48621628],
       [0.33423204, 0.84978756, 0.35483656, 0.56232577]])

## Array data
### dtype
NumPy's ndarrays are also efficient in part because all their elements must have the same type (usually numbers). You can check what the data type is by looking at the dtype attribute:

In [22]:
c = np.arange(1, 5)
print(c.dtype, c)

int32 [1 2 3 4]


In [23]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

float64 [1. 2. 3. 4.]


Instead of letting NumPy guess what data type to use, you can set it explicitly when creating an array by setting the dtype parameter:

In [24]:
d = np.arange(1, 5, dtype=np.complex64)
print(d.dtype, d)

complex64 [1.+0.j 2.+0.j 3.+0.j 4.+0.j]


Available data types include int8, int16, int32, int64, uint8|16|32|64, float16|32|64 and complex64|128. Check out [the documentation](https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) for the full list.

### itemsize
The itemsize attribute returns the size (in bytes) of each item:

In [25]:
e = np.arange(1, 5, dtype=np.complex64)
e.itemsize

8

### data buffer
An array's data is actually stored in memory as a flat (one dimensional) byte buffer. It is available via the data attribute (you will rarely need it, though).

In [26]:
f = np.array([[1,2],[1000, 2000]], dtype=np.int32)
f.data

### dive into arrays

In [27]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  
x1

array([5, 0, 3, 3, 7, 9])

Print the first 5 elements of an array: 


In [28]:
print(x1[:5])


[5 0 3 3 7]


Print the elements from the 6th and on of an array:


In [29]:
print(x1[5:])  


[9]


Print every two elements of an array:
  

In [30]:
print(x1[::2])

[5 3 7]


## Arithmetic operations
All the usual arithmetic operators (+, -, *, /, //, **, etc.) can be used with ndarrays. They apply elementwise:

In [31]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

a + b  = [19 27 35 43]
a - b  = [ 9 19 29 39]
a * b  = [70 92 96 82]
a / b  = [ 2.8         5.75       10.66666667 20.5       ]
a // b  = [ 2  5 10 20]
a % b  = [4 3 2 1]
a ** b = [537824 279841  32768   1681]


### Matrix addition and subtraction :

As we have seen previously, in order to perform additions and subtractions of two (or more) matrices,   
it's imperative that they have the same dimensions.

In [32]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = A + B
C

array([[ 8, 10, 12],
       [14, 16, 18]])

Same thing about subtraction...

In [33]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = A - B
C

array([[-6, -6, -6],
       [-6, -6, -6]])

If they do not have the same dimensions, then python will execute an error.

In [34]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[10,11]])
C = A + B
C

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

### Matrix multiplication : 

We can multiply the values of the array by a single multiplier.   
In this case, as can be seen all the values are multiplied by 2

In [ ]:
C = A * 2 
C

For multiplication with matrix, use function `dot()`. But don't forget, in the case of multiplications, the number of columns of A must correspond to the number of rows of B

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
print(A.shape, B.shape)

And that's the case here. 

In [ ]:
C = A.dot(B)
C

As you can see we have the same results as the multiplication example above.

But if the column number of A does not match the line name of B then we will have an error. 

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2,3],[4,5,6]])
A.dot(B)

To solve the problem we can make a transposition

In [ ]:
BT = B.T
BT.shape

We can now perform the multiplication

In [ ]:
A.dot(BT)

## Broadcasting
In general, when NumPy expects arrays of the same shape but finds that this is not the case, it applies the so-called broadcasting rules:

### First rule
If the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.

In [ ]:
h = np.arange(5).reshape(1, 1, 5)
h

Now let's try to add a 1D array of shape (5,) to this 3D array of shape (1,1,5). Applying the first rule of broadcasting!

In [ ]:
h + [10, 20, 30, 40, 50]  # same as: h + [[[10, 20, 30, 40, 50]]]

### Second rule
Arrays with a 1 along a particular dimension act as if they had the size of the array with the largest shape along that dimension. The value of the array element is repeated along that dimension.

In [ ]:
k = np.arange(6).reshape(2, 3)
k

Let's try to add a 2D array of shape (2,1) to this 2D ndarray of shape (2, 3). NumPy will apply the second rule of broadcasting:

In [ ]:
k + [[100], [200]]  # same as: k + [[100, 100, 100], [200, 200, 200]]

Combining rules 1 & 2, we can do this:

In [ ]:
k + [100, 200, 300]  # after rule 1: [[100, 200, 300]], and after rule 2: [[100, 200, 300], [100, 200, 300]]

And also, very simply:

In [ ]:
k + 1000  # same as: k + [[1000, 1000, 1000], [1000, 1000, 1000]]

## Mathematical and statistical functions
Many mathematical and statistical functions are available for ndarrays.

### ndarray methods
Some functions are simply ndarray methods, for example:

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
print(a)
print("mean =", a.mean())

Note that this computes the mean of all elements in the ndarray, regardless of its shape.

Here are a few more useful ndarray methods:

In [ ]:
for func in (a.min, a.max, a.sum, a.prod, a.std, a.var):
    print(func.__name__, "=", func())

These functions accept an optional argument axis which lets you ask for the operation to be performed on elements along the given axis. For example:

In [ ]:
c=np.arange(24).reshape(2,3,4)
c

In [ ]:
c.sum(axis=0)  # sum across matrices

In [ ]:
c.sum(axis=1)  # sum across rows

In [ ]:
c.sum(axis=(0,2))  # sum across matrices and columns

In [ ]:
0+1+2+3 + 12+13+14+15, 4+5+6+7 + 16+17+18+19, 8+9+10+11 + 20+21+22+23


## Universal functions
NumPy also provides fast elementwise functions called universal functions, or ufunc. They are vectorized wrappers of simple functions. For example square returns a new ndarray which is a copy of the original ndarray except that each element is squared:

In [ ]:
a = np.array([[-2.5, 3.1, 7], [10, 11, 12]])
np.square(a)

Here are a few more useful unary ufuncs:

In [ ]:
print("Original ndarray")
print(a)
for func in (np.abs, np.square, np.exp, np.sign, np.ceil, np.modf, np.isnan, np.cos):
    print("\n", func.__name__)
    print(func(a))